<!doctype html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <title>La Belle école</title>
    <link rel="stylesheet" href="styles.css">
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
</head>
<body>
    <h1>La belle école</h1>
    <div><?php if(isset($_GET['resultatDonne'])):?>
            <?php switch ($_GET['resultatDonne']):
                case 'OKMODIF': ?>
                    <b>Bien modifie !</b><?php ;
                    break;
                case 'OKINSERT':?>
                    <b>Bien inserée !</b><?php ;
                    break;
                case'OKSUPA20':?>
                    <b>Note usperieur ou inferieur à 20 !</b><?php ;
                    break;
                case'KOINSERT':?>
                    <b>Déjà existant !</b><?php ;
                    break;
                case 'OKSUPP':?>
                    <b>Bien supprimée !</b> <?php ;
                    break;
                default: ?>
                     <b>Erreur de modification</b>
            <?php endswitch; ?>
    <?php endif ?>
    </div>
    <table>
        <caption>Liste des classes de ma belle école</caption>
        <tr>
            <td>Les classes de notre collège : </td>
            <?php
            foreach($listeClasses as $uneClasse):?>
                <td><?=$uneClasse['classe']?></td>
             <?php endforeach;
            ?>
        </tr>
        <tr>
            <td>Nombre d'éléve par classe : </td>
            <?php
            foreach($listeClassesEffectif as $uneClasse):  ?>
                <td><?= $uneClasse['NombreElevesParClasse'];?></td>
            <?php endforeach; ?>
        </tr>
        <tr>
            <td>Moyenne par classe : </td>
            <?php
            foreach($listeClasses as $uneClasse) : ?>
                <td><?= $uneClasse['moyenneClasse']?></td>
        <?php endforeach; ?>
        </tr>
        <tr>
            <td>Moyen de l'école</td>
            <td colspan="<?php echo COUNT($listeClasses); ?>"><?php echo $MoyenneEcole['moyenneEcole'];?></td>
        </tr>
    </table>
    <div id="accordion">
        <h3>Ajouter éléve</h3>
        <div>
            <form action="insertion.php" method="post">
                <label for="nom">
                     <input type="text" name="nomAjout" placeholder="nom">
                </label>
                <label for="prenom">
                    <input type="text" name="prenomAjout" placeholder="prenom">
                </label>
                <select name="cid">
                     <?php foreach($listeClassesEffectif as $uneClasse):  ?>
                        <option value="<?= $uneClasse['cid'] ?>"><?= $uneClasse['classe'] ?></option>
                     <?php endforeach;?>
                </select>
                <input type="submit" value="Ajouter" name="ajouterEleve">
            </form>
        </div>
    </div>


    <div>
    </div>
    <ul class="titre"><li>Liste des éléves de ma belle école</li></ul>

    <ul style="background-color: aquamarine">
        <li>Nom</li>
        <li>Prenom</li>
        <li>Classe</li>
        <li>Moyenne éléve</li>
        <li>Moyenne Classe</li>
        <li>Ecartype absolut</li>
    </ul>
    </div>
        <div id="accordionEleve">
            <?php
            foreach($listeEleves as $unEleves)
            {?>
                <ul class="<?= $unEleves['nom'] ?> eleve">
                    <li><?= $unEleves['nom']?></li>
                    <li><?= $unEleves['prenom'] ?></li>
                    <li><?= $unEleves['classe']?>
                        <form action="modifier.php" method="post">
                            <select name="cid" id="classes">
                                <?php foreach($listeClassesEffectif as $uneClasse):  ?>
                                    <?php if($unEleves['classe'] === $uneClasse['classe']): ?>
                                        <option value="<?= $uneClasse['cid'];?>" selected><?= $uneClasse['classe'];?></option>
                                    <?php else : ?>
                                        <option value="<?= $uneClasse['cid'];?>"><?= $uneClasse['classe'];?></option>
                                    <?php endif; ?>
                                <?php endforeach; ?>
                            </select>
                            <input type="hidden" name="eid" value="<?= $unEleves['eid']; ?>">
                            <input type="submit" name="modificationClasse" value="modifier">
                        </form>
                    </li>
                    <?php ?>
                    <li> <?= $unEleves['moyenne'] ?></li>
                    <?php foreach($listeClasses as $moyenne)
                    {
                        if($moyenne['classe'] === $unEleves['classe'])
                        {
                            echo '<li>'. $moyenne['moyenneClasse'].'</li>';
                            echo '<li>'. round(abs($moyenne['moyenneClasse']-$unEleves['moyenne']),2).'</li>';
                        }
                    }?>
                </ul>
                <ul>
                    <li class="accordion">
                        <h3>Ajouter Note</h3>
                        <div>
                            <form action="insertion.php" method="post">
                                <label for="note">
                                    <input type="text" name="valeur" placeholder="La note">
                                </label>
                                <input type="hidden" name="eid" value="<?= $unEleves['eid']?>">
                                <label for="matiere">
                                    <select name="matiere" id="martier">
                                        <?php foreach($MatiereDisponible as $matiere){
                                            echo '<option value="'.$matiere['mid'].'">'.$matiere['matiere'].'</option>';
                                        }?>
                                    </select>
                                </label>
                                <input type="submit" value="Envoyer" name="submit">
                            </form>
                        </div>
                    </li>
                    <li>

                        <?php
                        foreach($listeNoteseleve as $eleve)
                        {
                            if($eleve['nom'] === $unEleves['nom'] )
                            {?>
                                <ul class="hidden" data-eleve="<?= $eleve['nom'];?>">
                                    <li>
                                        <form action="supprimer.php" method="post">
                                            <input type="hidden" value="<?= $eleve['nid']?>" name="nid">
                                            <input type="submit" value="supprimer" name="submit">
                                        </form>
                                    </li>
                                    <?php
                                    echo '<li>'.$eleve['matiere'] .' le '.date('Y-m-d').' : '.$eleve['valeur'].'</li>';
                                    foreach($MoyenneMatiere as $matiere)
                                    {
                                        if($eleve['matiere'] === $matiere['matiere'])
                                        {
                                            echo '<li>Moyenne de la Classe en '.$matiere['matiere'].' : '.$matiere['MoyenneMatiere'].'</li>';
                                        }
                                    }
                                    ?>
                                </ul>
                            <?php }
                        }; ?>
                        </li>
                </ul>
                        <?php } ?>

    <table>
        <caption>Toutes les matieres qui existes</caption>

            <tr>
                <td>
                    <form action="insertion.php" method="post">
                        <input type="text" placeholder="nouvelle matiere" name="matiereAjoutee">
                        <input type="submit" value="Ajouter" name="submit">
                    </form>
                </td>
            </tr>

        <?php
            foreach($MatiereDisponible as $matiere)
            { ?>
                <tr>
               <?= '<td>' . $matiere['matiere'] . '</td>';?>
                <td>
                    <form action="supprimer.php" method="post">
                        <input type="hidden" value="<?= $matiere['mid']?>" name="mid">
                        <input type="submit" value="supprimer" name="submit">
                    </form>
                </td>
                <td>
                    <form action="modifier.php" method="post">
                        <input type="hidden" value="<?= $matiere['mid']?>" name="mid">
                        <input type="text" value="<?= $matiere['matiere']?>" name="matiere">
                        <input type="submit" value="Modifier" name="submit">
                    </form>
                </td></tr>
            <?php };?>
    </table>
    <script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
    <script src="https://code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>
<script src="main.js"></script>
</body>
</html>